
CFLAGS = -g -Wall -ansi -DDEBUG -DLINUX
LDFLAGS = -I../ip-linux/ -I../tcp/ ../tcp/libtcp.a ../ip-linux/libip.a

all: tcp_actual_chksum tcp_connect tcp_listen tcp_connect_parallel tcp_generic_server tcp_large_transfer http_test_server http_test_client tcp_close_parallel_client tcp_close_parallel_server tcp_chop_server tcp_chop_client


tcp_actual_chksum: tcp_actual_chksum.c
	gcc $(CFLAGS) -o tcp_actual_chksum tcp_actual_chksum.c $(LDFLAGS)


tcp_connect: tcp_connect.c
	gcc $(CFLAGS) -o tcp_connect tcp_connect.c $(LDFLAGS)

tcp_listen: tcp_listen.c
	gcc $(CFLAGS) -o tcp_listen tcp_listen.c $(LDFLAGS)

tcp_connect_parallel: tcp_connect_parallel.c
	gcc $(CFLAGS) -o tcp_connect_parallel tcp_connect_parallel.c $(LDFLAGS)

tcp_generic_server: tcp_generic_server.c
	gcc $(CFLAGS) -o tcp_generic_server tcp_generic_server.c $(LDFLAGS)

tcp_large_transfer: tcp_large_transfer.c
	gcc $(CFLAGS) -o tcp_large_transfer tcp_large_transfer.c $(LDFLAGS)

http_test_server: http_test_server.c
	gcc $(CFLAGS) -o http_test_server http_test_server.c $(LDFLAGS)

http_test_client: http_test_client.c
	gcc $(CFLAGS) -o http_test_client http_test_client.c $(LDFLAGS)

tcp_close_parallel_client:  tcp_close_parallel_client.c
	gcc $(CFLAGS) -o tcp_close_parallel_client  tcp_close_parallel_client.c   $(LDFLAGS)

tcp_close_parallel_server:  tcp_close_parallel_server.c
	gcc $(CFLAGS) -o tcp_close_parallel_server tcp_close_parallel_server.c   $(LDFLAGS)
	
tcp_syn_ack_drop_server: tcp_syn_ack_drop_server.c
	gcc $(CFLAGS) -o tcp_syn_ack_drop_server  tcp_syn_ack_drop_server.c   $(LDFLAGS)

tcp_syn_ack_drop_client: tcp_syn_ack_drop_client.c
	gcc $(CFLAGS) -o tcp_syn_ack_drop_client  tcp_syn_ack_drop_client.c   $(LDFLAGS)

tcp_ack_drop_server: tcp_ack_drop_server.c
	gcc $(CFLAGS) -o tcp_ack_drop_server  tcp_ack_drop_server.c   $(LDFLAGS)

tcp_ack_drop_client: tcp_ack_drop_client.c
	gcc $(CFLAGS) -o tcp_ack_drop_client  tcp_ack_drop_client.c   $(LDFLAGS)

tcp_wrap_around_server: tcp_wrap_around_server.c
	gcc $(CFLAGS) -o tcp_wrap_around_server  tcp_wrap_around_server.c   $(LDFLAGS)

tcp_wrap_around_client: tcp_wrap_around_client.c
	gcc $(CFLAGS) -o tcp_wrap_around_client  tcp_wrap_around_client.c   $(LDFLAGS)

tcp_chop_server: tcp_chop_server.c
	gcc $(CFLAGS) -o tcp_chop_server tcp_chop_server.c $(LDFLAGS)

tcp_chop_client: tcp_chop_client.c
	gcc $(CFLAGS) -o tcp_chop_client tcp_chop_client.c $(LDFLAGS)

clean:
	rm -f tcp_actual_chksum tcp_connect tcp_listen tcp_connect_parallel tcp_generic_server tcp_large_transfer http_test_server http_test_client tcp_close_parallel_client tcp_close_parallel_server tcp_syn_ack_drop_server tcp_syn_ack_drop_client tcp_ack_drop_server tcp_ack_drop_client  tcp_wrap_around_client tcp_wrap_around_server tcp_chop_server tcp_chop_client
