
CC = gcc
CFLAGS = -g -Wall -DDEBUG=$(DEBUG) -DLINUX -ansi
LDFLAGS = -I. -I../ip-linux/ -I../tcp/ ../tcp/libtcp.a ../ip-linux/libip.a

all: httpd httpc

httpd: httpd.c http.c
	$(CC) $(CFLAGS) -o httpd httpd.c http.c $(LDFLAGS)

httpc: httpc.c
	$(CC) $(CFLAGS) -o httpc httpc.c http.c $(LDFLAGS)
	
clean:
	-rm httpd httpc


