
CC = gcc
AR = ar
RANLIB = ranlib
CFLAGS = -I. -I../ip-linux/ -g -Wall -DDEBUG -DLINUX -ansi

all: libtcp.a

libtcp.a: tcp.o
	$(AR) rv libtcp.a tcp.o
	$(RANLIB) libtcp.a

tcp.o: tcp.c tcp.h
	$(CC) $(CFLAGS) -c -o $@ $<

clean:
	-rm *.o
	-rm *.a

